SELECT @INC(dimentions), "@VAR2$" AS INDIC, @VAR0$ AS MONTH, @VAR1$ AS YEAR, "@VAR0$-@VAR1$" AS DATE,
CASE WHEN MONTH(TIMESTAMP) = @VAR0$ AND YEAR(TIMESTAMP) = @VAR1$ AND @VAR2$ IS NOT NULL
THEN @VAR2$ ELSE 0 END AS c_Y,
CASE WHEN MONTH(TIMESTAMP) = @VAR0$ AND YEAR(TIMESTAMP) = @VAR1$-1 AND @VAR2$ IS NOT NULL
THEN @VAR2$ ELSE 0 END AS c_Y_1,
CASE WHEN YEAR(TIMESTAMP) = @VAR1$ AND MONTH(TIMESTAMP) <= @VAR0$ AND @VAR2$ IS NOT NULL
THEN @VAR2$ ELSE 0 END AS c_Y_YTD,
CASE WHEN YEAR(TIMESTAMP) = @VAR1$-1 AND MONTH(TIMESTAMP) <= @VAR0$ AND @VAR2$ IS NOT NULL
THEN @VAR2$ ELSE 0 END AS c_Y_YTD_1,
CASE WHEN YEAR(TIMESTAMP) = @VAR1$ AND MONTH(TIMESTAMP) >= 1+ (@VAR0$-1)-((@VAR0$-1)%4) AND MONTH(TIMESTAMP) <= 5 AND @VAR2$ IS NOT NULL
THEN @VAR2$ ELSE 0 END AS c_Y_CTD,
CASE WHEN YEAR(TIMESTAMP) = @VAR1$-1 AND MONTH(TIMESTAMP) >= 1+ (@VAR0$-1)-((@VAR0$-1)%4) AND MONTH(TIMESTAMP) <= 5 AND @VAR2$ IS NOT NULL
THEN @VAR2$ ELSE 0 END AS c_Y_CTD_1,
CASE WHEN YEAR(TIMESTAMP) = @VAR1$ AND MONTH(TIMESTAMP) <= @VAR0$ AND @VAR2$ IS NOT NULL
THEN @VAR2$
WHEN YEAR(TIMESTAMP) = @VAR1$-1 AND MONTH(TIMESTAMP) >= @VAR0$+1 AND @VAR2$ IS NOT NULL
THEN @VAR2$
ELSE 0 END AS c_Y_MAT,
CASE WHEN YEAR(TIMESTAMP) = @VAR1$-1 AND MONTH(TIMESTAMP) <= @VAR0$ AND @VAR2$ IS NOT NULL
 THEN @VAR2$
WHEN YEAR(TIMESTAMP) = @VAR1$-2 AND MONTH(TIMESTAMP) >= @VAR0$+1 AND @VAR2$ IS NOT NULL
 THEN @VAR2$
ELSE 0 END AS c_Y_MAT_1
FROM [stallergenes_bi_v2_test.join_IGAP]