SELECT @INC(dimentions), MONTH, YEAR, DATE, INDIC,
SUM(c_Y) AS Y, SUM(c_Y_1) AS Y_1,
SUM(c_Y_CTD) AS Y_CTD, SUM(c_Y_CTD_1) AS Y_CTD_1,
SUM(c_Y_YTD) AS Y_YTD, SUM(c_Y_YTD_1) AS Y_YTD_1,
SUM(c_Y_MAT) AS Y_MAT, SUM(c_Y_MAT_1) AS Y_MAT_1
FROM
@INC(date:04:2013)
WHERE c_Y != 0 OR c_Y_1 != 0
GROUP EACH BY @INC(dimentions), MONTH, YEAR, DATE, INDIC